/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
//package kirjasto;

/**
 *
 * @author miksa
 */
public class AddBookWindow extends javax.swing.JFrame {
	private Bookshelf kirjahylly;
	private ListaMalli listaMalli;

	/**
	 * Creates new form AddBookWindow
	 */
	public AddBookWindow(Bookshelf kirjahylly, ListaMalli listaMalli) {
		this.kirjahylly = kirjahylly;
		this.listaMalli = listaMalli;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		writerNumberjTextField = new javax.swing.JTextField();
		bookNamejTextField = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		writerInformationjLabel = new javax.swing.JLabel();
		addBookjButton = new javax.swing.JButton();
		cancelBookAddjButton = new javax.swing.JButton();
		bookIsbnjTextField = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		bookYearjTextField = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		bookPricejTextField3 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();

		//setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		//this.dispose();
		setLocation(600, 200);
		jLabel1.setText("Writer");

		writerNumberjTextField.setPreferredSize(new java.awt.Dimension(50, 28));
		writerNumberjTextField
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						writerNumberjTextFieldActionPerformed(evt);
					}
				});

		jLabel2.setText("Book Name");

		addBookjButton.setText("Add");
		addBookjButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addBookjButtonActionPerformed(evt);
			}
		});

		cancelBookAddjButton.setText("Cancel");
		cancelBookAddjButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						cancelBookAddjButtonActionPerformed(evt);
					}
				});

		bookIsbnjTextField.setText("0");
		bookIsbnjTextField.setPreferredSize(new java.awt.Dimension(50, 28));

		jLabel3.setText("Isbn");

		bookYearjTextField.setText("0");
		bookYearjTextField.setPreferredSize(new java.awt.Dimension(50, 28));

		jLabel4.setText("Year");

		bookPricejTextField3.setText("0");
		bookPricejTextField3.setPreferredSize(new java.awt.Dimension(50, 28));

		jLabel5.setText("Price");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(256,
																		256,
																		256)
																.addComponent(
																		addBookjButton)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		cancelBookAddjButton)
																.addContainerGap(
																		166,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel3)
																								.addGap(70,
																										70,
																										70)
																								.addComponent(
																										bookIsbnjTextField,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel4)
																												.addComponent(
																														jLabel1)
																												.addComponent(
																														jLabel5))
																								.addGap(52,
																										52,
																										52)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														bookYearjTextField,
																														javax.swing.GroupLayout.Alignment.TRAILING,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														bookPricejTextField3,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														writerNumberjTextField,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										writerInformationjLabel,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										297,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel2)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										bookNamejTextField,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										189,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addGap(0,
																		0,
																		Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														bookNamejTextField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						bookIsbnjTextField,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel3))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						bookYearjTextField,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel4))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						bookPricejTextField3,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel5))
																.addGap(10, 10,
																		10)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						writerNumberjTextField,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addComponent(
														writerInformationjLabel,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														30,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(42, 42, 42)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(addBookjButton)
												.addComponent(
														cancelBookAddjButton))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Lets add new book to database button happens
	 * 
	 * @param evt
	 */
	private void addBookjButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addBookjButtonActionPerformed
		System.out.println("Debug: Add");
		String nimi = bookNamejTextField.getText();
		String isbn1 = bookIsbnjTextField.getText();
		int year = Integer.parseInt(bookYearjTextField.getText());
		float price = Float.parseFloat(bookPricejTextField3.getText());
		int wno = Integer.parseInt(writerNumberjTextField.getText());
		// TODO: Make sure that writernumber has real value(from modell??)
		kirjahylly.addBook(nimi, isbn1, year, price, wno);
		bookNamejTextField.setText("");
		bookIsbnjTextField.setText("");
		bookPricejTextField3.setText("");
		bookYearjTextField.setText("");
		writerNumberjTextField.setText("");
		writerInformationjLabel.setText("");
		kirjahylly.updateLists();
		this.setVisible(false);
	}// GEN-LAST:event_addBookjButtonActionPerformed

	private void cancelBookAddjButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelBookAddjButtonActionPerformed
		System.out.println("Debug: Cancel");
		writerNumberjTextField.setText("");
		bookNamejTextField.setText("");
		this.setVisible(false);
	}// GEN-LAST:event_cancelBookAddjButtonActionPerformed

	private void writerNumberjTextFieldActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_writerNumberjTextFieldActionPerformed
		int apu = Integer.parseInt(writerNumberjTextField.getText());
		writerInformationjLabel.setText((String) listaMalli.getElementAt(apu));
	}// GEN-LAST:event_writerNumberjTextFieldActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AddBookWindow.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AddBookWindow.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AddBookWindow.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AddBookWindow.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				// new AddBookWindow().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addBookjButton;
	private javax.swing.JTextField bookIsbnjTextField;
	private javax.swing.JTextField bookNamejTextField;
	private javax.swing.JTextField bookPricejTextField3;
	private javax.swing.JTextField bookYearjTextField;
	private javax.swing.JButton cancelBookAddjButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel writerInformationjLabel;
	private javax.swing.JTextField writerNumberjTextField;
	// End of variables declaration//GEN-END:variables
}
